[tool.pixi.workspace]
authors = ["Enrique Babio <enrique.babio@skydweller.aero>"]
channels = ["conda-forge"]
name = "lifting_line"
platforms = ["win-64"]
version = "0.1.0"

[tool.pixi.tasks]

# Default environment
[tool.pixi.dependencies]
python = "3.12.*"
numpy = "*"
scipy = "*"
matplotlib = "*"

[tool.pixi.pypi-dependencies]
lifting_line = { path = ".", editable = true }

# Testing environent
[tool.pixi.feature.test.dependencies]
pytest = "*"

# State Environments
[tool.pixi.environments]
test = ["test"]

